### ISSUE TITLE
Schematic has two pin D1 labels - causes issues with PSRAM_CS

### ISSUE THREAD

**Issue by sandman72** [tvlad1234/linux-ch32v003#1]
The schematic symbol of the CH32v003 has two pin label for D1 (Pin 18 and Pin 20).
Pin 20 (PD3) should be labeled **PD3_A4_T1CH2** and is the correct one to connect to PSRAM_CS

I found this while using the schematic and a dev board. Connecting PSRAM_CS to the dev boards pin D1 didn't work. Checking the thing_config.h revealed that it actually should have been pin D3...

(and BTW: awesome work! 😃 )

**Comment by tvlad1234** [comment]
Wow, I've just noticed that, when developing I referenced the pinout in the datasheet and didn't notice the hiccup in the schematic symbol. Thank you for bringing this up, I am now fixing that and commiting it to the repo. I am happy that you like this project! 😄

**Comment by tvlad1234** [comment]
fixed. let me know how using this project goes for you, i would love to see how others use it and what their hardware setup looks like!
